name: Android CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# همه دستورها داخل پوشه پروژه اجرا شود
defaults:
  run:
    working-directory: "VPN APP"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # مسیر نسبت به ریشه ریپو است (نه working-directory)
          path: VPN APP/app/build/outputs/apk/debug/app-debug.apk
