name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: "VPN APP"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: VPN APP/app/build/outputs/apk/debug/app-debug.apk
